# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/output.xdc

# Block Designs: bd/Diagramm/Diagramm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagramm || ORIG_REF_NAME==Diagramm} -quiet] -quiet

# IP: bd/Diagramm/ip/Diagramm_processing_system7_0_0/Diagramm_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagramm_processing_system7_0_0 || ORIG_REF_NAME==Diagramm_processing_system7_0_0} -quiet] -quiet

# IP: bd/Diagramm/ip/Diagramm_my_ip_v3_0_0/Diagramm_my_ip_v3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagramm_my_ip_v3_0_0 || ORIG_REF_NAME==Diagramm_my_ip_v3_0_0} -quiet] -quiet

# IP: bd/Diagramm/ip/Diagramm_ps7_0_axi_periph_0/Diagramm_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagramm_ps7_0_axi_periph_0 || ORIG_REF_NAME==Diagramm_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Diagramm/ip/Diagramm_rst_ps7_0_50M_0/Diagramm_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagramm_rst_ps7_0_50M_0 || ORIG_REF_NAME==Diagramm_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Diagramm/ip/Diagramm_auto_pc_0/Diagramm_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagramm_auto_pc_0 || ORIG_REF_NAME==Diagramm_auto_pc_0} -quiet] -quiet

# XDC: bd/Diagramm/Diagramm_ooc.xdc
