# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anzhelika/projekt/myIpv3/VivadoDesign/VivadoDesign.srcs/sources_1/bd/Diagramm/ip/Diagramm_auto_pc_0/Diagramm_auto_pc_0.xci
# IP: The module: 'Diagramm_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anzhelika/projekt/myIpv3/VivadoDesign/VivadoDesign.srcs/sources_1/bd/Diagramm/ip/Diagramm_auto_pc_0/Diagramm_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Diagramm_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/anzhelika/projekt/myIpv3/VivadoDesign/VivadoDesign.srcs/sources_1/bd/Diagramm/ip/Diagramm_auto_pc_0/Diagramm_auto_pc_0.xci
# IP: The module: 'Diagramm_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anzhelika/projekt/myIpv3/VivadoDesign/VivadoDesign.srcs/sources_1/bd/Diagramm/ip/Diagramm_auto_pc_0/Diagramm_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Diagramm_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
